const items = [
  {
    name: "Tent",
    owner: "Sean",
    description: "Sleeping shelter",
    category: ["camping", "shelter"],
    complete: false,
    starred: true,
  },
  {
    name: "Sleeping bag",
    owner: "Sean",
    description: "Keeps you warm at night",
    category: ["camping", "shelter"],
    complete: false,
    starred: false,
  },
  {
    name: "Camp stove",
    owner: "Sean",
    description: "For cooking meals",
    category: ["camping", "food"],
    complete: true,
    starred: true,
  },
  {
    name: "Band Aids",
    owner: "Sean",
    description: "For cooking meals",
    category: ["first aid"],
    complete: true,
    starred: true,
  },
  {
    name: "Tweezers",
    owner: "Sean",
    description: "For cooking meals",
    category: ["first aid"],
    complete: true,
    starred: true,
  },
  {
    name: "Tourniquette",
    owner: "Sean",
    description: "For cooking meals",
    category: ["first aid"],
    complete: true,
    starred: true,
  },
  {
    name: "Cooler",
    owner: "Elizabeth",
    description: "Keeps food and drinks cold",
    category: ["camping", "food"],
    complete: true,
    starred: false,
  },
];

module.exports = items;
